#ifndef UPPSALA_RENAN_GRAPHENE_MOIRRE_PROJECT_REVIEW_GRAPHENE_SET_GEOMETRY
#define UPPSALA_RENAN_GRAPHENE_MOIRRE_PROJECT_REVIEW_GRAPHENE_SET_GEOMETRY

class SetGeometry{
public:

    

    SetGeometry();

private:    
}

#endif